const fs=require('fs');
const P='D:/Desktop/策划笔试/方块星球-v2/';
const g=fs.readFileSync(P+'game.js','utf8');
const h=fs.readFileSync(P+'index.html','utf8');
const t=(n,ok)=>console.log((ok?'OK  ':'FAIL')+' '+n);
console.log('=== 剪刀体系彻底清除 ===');
t('shears 0 残留', /shears/i.test(g)===false);
t('「剪刀」0 残留', /剪刀/.test(g)===false);
t('BELT 无 shears', /id:'shears'/.test(g)===false);
t('TOOL_IDS 无 shears', /'sword','shears'/.test(g)===false);
t('extras 无 shears', /shears:false/.test(g)===false);
console.log('=== 连带清除的补给箱/绵羊 ===');
t('空手提示不再提补给箱', /补给箱交互/.test(g)===false);
t('标签映射无补给箱/绵羊', /'空补给箱'|'剪刀补给箱'|'绵羊 · 剪毛'/.test(g)===false);
t('对话标题映射无补给箱/绵羊', /a\.type==='sheep'\?'绵羊'/.test(g)===false);
t('绘制分支无补绘箱/绵羊', /else if\(a\.type==='chest'\)\{ctx|else if\(a\.type==='sheep'\)\{if\(encounterTime/.test(g)===false);
t('interactEncounter 无补给箱/绵羊', /取得剪刀|先去左下方补给箱拿剪刀/.test(g)===false);
t('dialogueCopy 无补给箱/绵羊', /箱子里放着一把剪刀|使用剪刀 · 羊毛/.test(g)===false);
t('confirmDialogue 无补给箱/绵羊', /剪刀已放入背包|获得两份羊毛/.test(g)===false);
t('beltAct 无 shears 特判', /held==='shears'/.test(g)===false);
t('updateEncounters 无绵羊生长', /a\.type==='sheep'&&a\.sheared/.test(g)===false);
console.log('\n=== 残留引用清单 ===');
['shears','剪刀','绵羊','sheep','chest','补给箱','wool','羊毛'].forEach(k=>{
  const hits=[];g.split(/\r?\n/).forEach((l,i)=>{if(l.includes(k))hits.push(i+1)});
  console.log('  '+k.padEnd(8)+' → '+(hits.length?hits.length+' 处  行: '+hits.join(','):'0 处 ✅'));
});
console.log('\n--- 剩余逐行（应为不可达死代码/注释）---');
g.split(/\r?\n/).forEach((l,i)=>{if(/sheep|chest|wool|绵羊|羊毛|补给箱/i.test(l))console.log('  L'+(i+1)+': '+l.trim().slice(0,140))});
console.log('\n=== 回归 ===');
t('DAY4 终点开关完好', /function goalShown\(\)\{return day!==3\|\|!!extras\.metFarmer\}/.test(g));
t('DAY1/DAY3 水桶隐藏完好', /const showB=\!\(day===0\|\|day===2\)/.test(g));
t('宝箱逻辑完好', /function lootTreasure\(a\)\{/.test(g));
t('火晶矿需铁镐完好', /if\(n\.type==='fire_ore'\)\{\s*\n\s*if\(!extras\.ironPickaxe\)/.test(g));
t('DAY2 两段式对话完好', /if\(farmerTalk===0\)/.test(g));
t('僵尸攻击完好', /function attackZombie\(a\)\{/.test(g));
const bal=(s,c)=>s.split(c).length-1;
console.log('  括号配平 { } : '+bal(g,'{')+' / '+bal(g,'}')+'    ( ) : '+bal(g,'(')+' / '+bal(g,')'));
console.log('  版本戳 game.js → '+((h.match(/game\.js\?v=([\d-]+)/)||[])[1]||'?'));
