const fs=require('fs');
const vm=require('vm');
const assert=require('assert');
const source=fs.readFileSync(__dirname+'/game.js','utf8');
class Element{
  constructor(){this.style={};this.classList={add(){},remove(){},toggle(){}};this.clientWidth=1000;this.clientHeight=700;this.width=0;this.height=0;this.innerHTML='';this.textContent=''}
  addEventListener(){} setAttribute(){} querySelector(){return new Element()}
  getBoundingClientRect(){return{left:0,top:0,width:1000,height:700}}
  getContext(){const gradient={addColorStop(){}};return new Proxy({createRadialGradient(){return gradient}}, {get(obj,k){return obj[k]||function(){}}})}
}
const elements=new Map(),cards=[new Element(),new Element(),new Element()];
const document={getElementById(id){if(!elements.has(id))elements.set(id,new Element());return elements.get(id)},querySelectorAll(q){return q==='.day-card'?cards:[]},addEventListener(){}};
const localStorage={getItem(){return null},setItem(){}};
const intervals=new Map();let intervalId=0;
const context={document,window:{addEventListener(){}},localStorage,devicePixelRatio:1,setInterval(fn){intervals.set(++intervalId,fn);return intervalId},clearInterval(id){intervals.delete(id)},setTimeout(){return 1},clearTimeout(){},requestAnimationFrame(){},console};
const marker="window.addEventListener('resize',resize);updateHome();requestAnimationFrame(animate);";
assert(source.includes(marker));
const exposed="globalThis.test={start,interact,craft,finish,move,pathTo,terrain,isWater,setSoilMode,soilCheck,tradeWheat,updateEncounters,showBag,closeMobilePanels,confirmDialogue,animate,setPos:(x,y,z)=>{player={x,y,z}},setFocus:(x,y)=>{focus={x,y}},setBag:(type,n)=>{bag[type]=n},getBag:()=>({...bag}),getExtras:()=>({...extras}),getActors:()=>actors.map(a=>({...a})),getState:()=>({maxUnlocked,day,player,remaining,uiMode,soilMode,tickHandle,ladderBuilt,holeDug,bridges:[...bridges],brokenRocks:[...brokenRocks]})};";
vm.runInNewContext(source.replace(marker,exposed+marker),context);
const t=context.test;

t.start(0);t.setBag('wood',2);t.setPos(4,4,0);t.setFocus(5,4);t.interact();assert(t.getState().bridges.includes('5,4'),'DAY1 bridge');t.setPos(8,3,0);t.setFocus(8,4);t.interact();assert.equal(t.getBag().ore,1,'DAY1 ore');t.finish('test');assert.equal(t.getState().maxUnlocked,2,'DAY2 unlock');

t.start(1);t.setBag('wood',2);t.setPos(5,4,0);t.setFocus(6,4);t.interact();assert(t.getState().ladderBuilt,'DAY2 ladder built');t.interact();assert.equal(t.getState().player.z,2,'DAY2 climbed');t.setPos(8,4,2);t.setFocus(8,3);t.interact();assert.equal(t.getBag().ore,1,'DAY2 ore');t.finish('test');assert.equal(t.getState().maxUnlocked,3,'DAY3 unlock');

t.start(2);t.setBag('wood',3);t.setBag('stone',2);t.setPos(2,4,0);t.setFocus(3,4);t.interact();t.interact();assert.equal(t.getState().player.z,2,'DAY3 climbed');t.setPos(4,4,2);t.setFocus(4,3);t.interact();assert.equal(t.getBag().stone,3,'DAY3 high stone');t.craft();t.setPos(6,6,0);t.setFocus(7,6);t.interact();assert(t.getState().holeDug,'DAY3 hole dug');t.interact();assert.equal(t.getState().player.z,-2,'DAY3 descended');t.setPos(9,6,-2);t.setFocus(9,7);t.interact();assert.equal(t.getBag().ore,1,'DAY3 ore');
console.log('PASS: DAY1 bridge and unlock, DAY2 climb and unlock, DAY3 dig and collect');

function walkTo(x,y){const path=t.pathTo(x,y);assert(path,`reachable ${x},${y}`);for(const step of path){const p=t.getState().player;t.move(step.x-p.x,step.y-p.y)}assert.equal(t.getState().player.x,x);assert.equal(t.getState().player.y,y)}
t.start(0);walkTo(1,2);t.setFocus(1,1);t.interact();assert.equal(t.getExtras().wheat,3,'ripe wheat harvested');t.interact();assert.equal(t.getExtras().wheat,3,'cannot spam unripe wheat');walkTo(2,5);t.setFocus(2,6);elements.get('interact').onclick();assert.equal(t.getState().uiMode,'dialogue','touch E opens full-screen dialogue');const dialogTime=t.getState().remaining;intervals.get(t.getState().tickHandle)();assert.equal(t.getState().remaining,dialogTime,'dialogue pauses clock');t.move(-1,0);assert.equal(t.getState().player.x,2,'dialogue blocks movement');t.tradeWheat();assert.equal(t.getExtras().emerald,1,'farmer gives emerald');assert.equal(t.getExtras().wheat,0,'trade consumes wheat');t.tradeWheat();assert.equal(t.getExtras().emerald,1,'no free trade');t.closeMobilePanels();t.updateEncounters(20);walkTo(1,2);t.setFocus(1,1);t.interact();assert.equal(t.getExtras().wheat,3,'wheat regrows');t.finish('NPC test');assert(elements.get('resultItems').innerHTML.includes('绿宝石 ×1'),'bonus on settlement');

function useNPC(){t.interact();t.confirmDialogue();t.closeMobilePanels()}
t.start(1);walkTo(3,7);t.setFocus(4,7);useNPC();assert.equal(t.getExtras().wool,0,'shears required');walkTo(2,7);t.setFocus(2,6);t.interact();assert.equal(t.getExtras().shears,false,'opening dialogue does not auto-claim');t.confirmDialogue();assert(t.getExtras().shears,'chest dialogue grants shears');t.closeMobilePanels();walkTo(3,7);t.setFocus(4,7);useNPC();assert.equal(t.getExtras().wool,2,'shearing grants wool');useNPC();assert.equal(t.getExtras().wool,2,'no repeat shearing while bare');t.updateEncounters(12);assert.equal(t.getActors().find(a=>a.type==='sheep').sheared,false,'grass restores coat');useNPC();assert.equal(t.getExtras().wool,4,'can shear regrown coat');t.updateEncounters(12);assert(t.getActors().find(a=>a.type==='sheep').sheared,'dirt cannot immediately feed sheep again');t.updateEncounters(6);assert.equal(t.getActors().find(a=>a.type==='sheep').sheared,false,'regrowth waits for grass');t.start(1);assert.equal(t.getExtras().wool,0,'replay clears rewards');assert.equal(t.getExtras().shears,false,'replay closes chest');

t.start(2);t.setPos(7,7,-2);t.updateEncounters(.8);assert(t.getActors()[0].fuse>0,'creeper starts fuse nearby');t.setPos(1,4,0);t.updateEncounters(.1);assert.equal(t.getActors()[0].fuse,0,'retreat cancels fuse across layers');t.setPos(7,7,-2);const before=t.getState().remaining;t.updateEncounters(1.6);assert.equal(t.getActors()[0].alive,false,'creeper explodes');assert(t.getState().brokenRocks.includes('8,6'),'explosion opens adjacent rock');assert.equal(t.getState().remaining,before-15,'blast costs 15 seconds');assert.equal(t.getState().player.x,7,'safe cave respawn');assert.equal(t.getState().player.y,6);assert.equal(t.getBag().ore,0,'main objective remains uncollected');walkTo(9,6);t.setFocus(9,7);t.interact();assert.equal(t.getBag().ore,1,'main objective still reachable after explosion');
console.log('PASS: farmer trade, crop regrowth, shears chest, sheep grazing, NPC reward/reset, creeper fuse/cancel/blast and post-blast route');
t.start(2);t.setPos(7,7,-2);t.updateEncounters(.3);const fuse=t.getActors()[0].fuse;t.showBag();const bagTime=t.getState().remaining;intervals.get(t.getState().tickHandle)();t.animate(0);t.animate(100);assert.equal(t.getState().remaining,bagTime,'bag pauses clock');assert.equal(t.getActors()[0].fuse,fuse,'bag pauses creeper');elements.get('chooseStairs').onclick();t.closeMobilePanels();intervals.get(t.getState().tickHandle)();assert.equal(t.getState().remaining,bagTime-1,'closing panel resumes clock');assert.equal(t.getState().uiMode,null,'panel closes');
console.log('PASS: touch dialogue opening, confirmation, movement lock, bag/dialogue timer pause and enemy pause/resume');

function soil(mode,x,y){if(t.getState().soilMode!==mode)t.setSoilMode(mode);t.setFocus(x,y);t.interact()}
function normal(){const m=t.getState().soilMode;if(m!=='interact')t.setSoilMode(m)}
t.start(0);walkTo(2,4);soil('dig',2,5);assert.equal(t.terrain(2,5),-1,'dig changes terrain');assert.equal(t.getBag().dirt,1,'dig stores dirt');walkTo(4,4);soil('place',5,4);assert.equal(t.isWater(5,4),false,'dirt fills river');assert.equal(t.getBag().dirt,0,'placement consumes dirt');walkTo(6,4);soil('dig',5,4);assert(t.isWater(5,4),'reclaim bridge restores water');assert.equal(t.getBag().dirt,1,'reclaim one block only');assert.equal(t.pathTo(4,4),null,'removed bridge breaks route');soil('place',5,4);assert(t.pathTo(4,4),'replaced bridge restores route');assert.equal(t.getBag().dirt,0,'no duplication');normal();walkTo(8,3);t.setFocus(8,4);t.interact();assert.equal(t.getBag().ore,1,'DAY1 reachable using dirt only');

t.start(1);soil('dig',2,4);walkTo(5,6);soil('place',6,6);assert.equal(t.terrain(6,6),1,'stacked soil makes step');const ascent=t.pathTo(6,5);assert(ascent&&ascent.some(p=>p.x===6&&p.y===6),'pathfinder uses soil step');walkTo(6,5);assert.equal(t.getState().player.z,2,'player climbs built step');normal();walkTo(7,3);t.setFocus(8,3);t.interact();assert.equal(t.getBag().ore,1,'DAY2 without ladder');

t.start(2);walkTo(6,6);soil('dig',6,7);t.move(0,1);assert.equal(t.getState().player.z,-1,'descend excavated step');t.move(1,0);assert.equal(t.getState().player.z,-2,'enter cave without fixed hole');soil('place',7,8);t.move(0,1);assert.equal(t.getState().player.z,-1,'climb placed cave block');t.move(-1,0);assert.equal(t.getState().player.z,0,'dirt creates return route');soil('dig',7,8);assert.equal(t.terrain(7,8),-2,'cave block reclaimed');assert.equal(t.getBag().dirt,1);assert(t.soilCheck('dig',7,8),'cannot mine unlimited soil from stone cave');

t.start(0);soil('dig',1,5);soil('dig',1,5);soil('dig',1,5);assert.equal(t.getBag().dirt,2,'bedrock caps natural excavation');soil('place',1,5);soil('place',1,5);assert.equal(t.terrain(1,5),0,'restore original ground');assert.equal(t.getBag().dirt,0);soil('place',1,5);assert.equal(t.terrain(1,5),0,'no free placement');const beforeSoil=t.terrain(2,4);t.showBag();soil('dig',2,4);assert.equal(t.terrain(2,4),beforeSoil,'bag blocks terrain edits');t.closeMobilePanels();t.start(0);assert.equal(t.getBag().dirt,0,'restart clears dirt');assert.equal(t.terrain(1,5),0,'restart resets terrain');assert.equal(t.getState().soilMode,'interact','restart resets mode');
console.log('PASS: all-day dig/place routes, river restoration, step pathfinding, cave return, conservation, bedrock and reset');
